import datetime

COMPLIANCE_MAP = {
    "stale_account":         {"soc2": "CC6.2", "iso": "A.9.2.5", "nist": "AC-2(3)", "pci": "Req 7.2.1", "cmmc": "AC.L1-3.1.1"},
    "admin_without_mfa":     {"soc2": "CC6.1", "iso": "A.9.4.2", "nist": "IA-5",    "pci": "Req 8.4.2", "cmmc": "IA.L2-3.5.3"},
    "admin_missing_manager": {"soc2": "CC6.3", "iso": "A.9.2.2", "nist": "AC-2",    "pci": "Req 7.2.4", "cmmc": "AC.L1-3.1.2"},
    "external_access":       {"soc2": "CC6.6", "iso": "A.9.4.1", "nist": "AC-17",   "pci": "Req 7.3.1", "cmmc": "AC.L2-3.1.14"},
    "security_hub":          {"soc2": "CC7.1", "iso": "A.12.6.1","nist": "SI-2",    "pci": "Req 6.3.3", "cmmc": "SI.L1-3.14.1"},
}

SEVERITY_COLORS = {"High": "#c0392b", "Medium": "#e67e22", "Low": "#27ae60"}


def render(findings: dict, narrative: str, account_id: str, date: str) -> str:
    iam = findings.get("iam", [])
    access_analyzer = findings.get("access_analyzer", [])
    security_hub = findings.get("security_hub", [])
    all_findings = iam + access_analyzer + security_hub

    high_count = sum(1 for f in all_findings if f.get("severity", "").lower() == "high")
    risk_label, risk_color = _risk_badge(high_count)
    formatted_date = f"{date[:4]}-{date[4:6]}-{date[6:]}" if len(date) == 8 else date

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Access Review Report — {formatted_date}</title>
<style>
  body {{ font-family: Arial, sans-serif; margin: 40px; color: #2c3e50; background: #f9f9f9; }}
  h1 {{ color: #2c3e50; }}
  h2 {{ color: #34495e; border-bottom: 2px solid #bdc3c7; padding-bottom: 6px; }}
  .badge {{ display: inline-block; padding: 4px 12px; border-radius: 4px; color: white; font-weight: bold; }}
  table {{ width: 100%; border-collapse: collapse; margin-bottom: 30px; background: white; }}
  th {{ background: #2c3e50; color: white; padding: 10px; text-align: left; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #ecf0f1; }}
  tr:hover {{ background: #f5f6fa; }}
  .sev {{ padding: 2px 8px; border-radius: 3px; color: white; font-size: 0.85em; }}
  .narrative {{ background: white; padding: 20px; border-left: 4px solid #2980b9; margin-bottom: 30px; }}
  footer {{ color: #95a5a6; font-size: 0.85em; margin-top: 40px; text-align: center; }}
</style>
</head>
<body>
<h1>AWS Automated Access Review</h1>
<p>
  <strong>Account:</strong> {account_id} &nbsp;|&nbsp;
  <strong>Date:</strong> {formatted_date} &nbsp;|&nbsp;
  <strong>Risk Posture:</strong>
  <span class="badge" style="background:{risk_color}">{risk_label}</span>
</p>

<h2>Executive Summary</h2>
<div class="narrative">{narrative}</div>

<h2>IAM Findings ({len(iam)})</h2>
{_findings_table(iam, ["username", "finding_type", "severity", "detail"])}

<h2>Access Analyzer Findings ({len(access_analyzer)})</h2>
{_findings_table(access_analyzer, ["resource_type", "resource_arn", "principal", "access_level", "severity"])}

<h2>Security Hub Findings ({len(security_hub)})</h2>
{_findings_table(security_hub, ["control_id", "title", "severity", "remediation"])}

<h2>Compliance Control Mapping</h2>
{_compliance_table(iam, access_analyzer, security_hub)}

<footer>
  Generated by AWS Automated Access Review &mdash;
  {datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}
</footer>
</body>
</html>"""


def _risk_badge(high_count):
    if high_count >= 3:
        return "High Risk", "#c0392b"
    if high_count >= 1:
        return "Medium Risk", "#e67e22"
    return "Low Risk", "#27ae60"


def _severity_cell(severity):
    color = SEVERITY_COLORS.get(severity, "#7f8c8d")
    return f'<span class="sev" style="background:{color}">{severity}</span>'


def _findings_table(findings, columns):
    if not findings:
        return "<p><em>No findings in this domain.</em></p>"
    headers = "".join(f"<th>{c.replace('_', ' ').title()}</th>" for c in columns)
    rows = ""
    for f in findings:
        cells = "".join(
            f"<td>{_severity_cell(f.get(col, ''))}</td>" if col == "severity"
            else f"<td>{f.get(col, '')}</td>"
            for col in columns
        )
        rows += f"<tr>{cells}</tr>"
    return f"<table><tr>{headers}</tr>{rows}</table>"


def _compliance_table(iam, access_analyzer, security_hub):
    rows = ""
    seen = set()
    for f in iam:
        ft = f.get("finding_type", "")
        if ft not in seen and ft in COMPLIANCE_MAP:
            seen.add(ft)
            m = COMPLIANCE_MAP[ft]
            label = ft.replace("_", " ").title()
            rows += f"<tr><td>{label}</td><td>{m['soc2']}</td><td>{m['iso']}</td><td>{m['nist']}</td><td>{m['pci']}</td><td>{m['cmmc']}</td></tr>"
    if access_analyzer:
        m = COMPLIANCE_MAP["external_access"]
        rows += f"<tr><td>External Access Exposure</td><td>{m['soc2']}</td><td>{m['iso']}</td><td>{m['nist']}</td><td>{m['pci']}</td><td>{m['cmmc']}</td></tr>"
    if security_hub:
        m = COMPLIANCE_MAP["security_hub"]
        rows += f"<tr><td>Security Hub IAM Finding</td><td>{m['soc2']}</td><td>{m['iso']}</td><td>{m['nist']}</td><td>{m['pci']}</td><td>{m['cmmc']}</td></tr>"
    return (
        "<table>"
        "<tr><th>Finding Type</th><th>SOC 2</th><th>ISO 27001</th><th>NIST 800-53</th><th>PCI-DSS 4.0</th><th>CMMC</th></tr>"
        f"{rows}"
        "</table>"
    )
